language: python
sudo: false
matrix:
    include:
        - python: 2.7
        - python: 3.5
        - python: 3.6
addons:
  apt:
    packages:
    - libhdf5-serial-dev 
install:
  - pip install .
  - pip install coveralls
  - pip install numpy
script:
  nosetests test/unittests --with-coverage --cover-package=nineml
after_success:
  coveralls
